version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "docker_rails_development"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - 3003:3003
    depends_on:
      - db
    # command: bash -c "gem install nokogiri --platform=ruby && bundle exec rails s -p 3000 -b '0.0.0.0'"

volumes:
  postgresdb:
